"""Changed default value

Revision ID: 8dcdb38d0a42
Revises: 90c9d9c6443f
Create Date: 2026-06-09 12:30:58.116008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8dcdb38d0a42'
down_revision: Union[str, Sequence[str], None] = '90c9d9c6443f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bugs', sa.Column('priority', sa.String(), nullable=False))
    op.alter_column('bugs', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('bugs', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('bugs', 'type',
               existing_type=postgresql.ENUM('bug', 'feature', name='bug_type'),
               type_=sa.String(),
               nullable=False)
    op.alter_column('bugs', 'status',
               existing_type=postgresql.ENUM('new', 'started', 'completed', 'resolved', name='bug_status'),
               type_=sa.String(),
               nullable=False)
    op.alter_column('bugs', 'screenshot',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('bugs', 'project_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('bugs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_bugs_id'), 'bugs', ['id'], unique=False)
    op.drop_constraint(op.f('bugs_created_by_fkey'), 'bugs', type_='foreignkey')
    op.drop_constraint(op.f('bugs_assigned_to_fkey'), 'bugs', type_='foreignkey')
    op.create_foreign_key(None, 'bugs', 'profiles', ['created_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'bugs', 'profiles', ['assigned_to'], ['id'], ondelete='SET NULL')
    op.drop_column('bugs', 'updated_at')
    op.alter_column('profiles', 'full_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('profiles', 'role',
               existing_type=postgresql.ENUM('Manager', 'Developer', 'QA', name='user_role'),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint(op.f('profiles_id_fkey'), 'profiles', type_='foreignkey')
    op.drop_column('profiles', 'created_at')
    op.alter_column('project_members', 'project_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_constraint(op.f('project_members_project_id_user_id_key'), 'project_members', type_='unique')
    op.drop_column('project_members', 'joined_at')
    op.drop_column('project_members', 'id')
    op.alter_column('projects', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('projects', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('projects', 'logo',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.drop_constraint(op.f('projects_created_by_fkey'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'profiles', ['created_by'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_created_by_fkey'), 'projects', 'profiles', ['created_by'], ['id'])
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'logo',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('projects', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('projects', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('project_members', sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False))
    op.add_column('project_members', sa.Column('joined_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('project_members_project_id_user_id_key'), 'project_members', ['project_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('project_members', 'project_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.add_column('profiles', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('profiles_id_fkey'), 'profiles', 'users', ['id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    op.alter_column('profiles', 'role',
               existing_type=sa.String(),
               type_=postgresql.ENUM('Manager', 'Developer', 'QA', name='user_role'),
               existing_nullable=False)
    op.alter_column('profiles', 'full_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('bugs', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bugs', type_='foreignkey')
    op.drop_constraint(None, 'bugs', type_='foreignkey')
    op.create_foreign_key(op.f('bugs_assigned_to_fkey'), 'bugs', 'profiles', ['assigned_to'], ['id'])
    op.create_foreign_key(op.f('bugs_created_by_fkey'), 'bugs', 'profiles', ['created_by'], ['id'])
    op.drop_index(op.f('ix_bugs_id'), table_name='bugs')
    op.alter_column('bugs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('bugs', 'project_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('bugs', 'screenshot',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('bugs', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('new', 'started', 'completed', 'resolved', name='bug_status'),
               nullable=True)
    op.alter_column('bugs', 'type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('bug', 'feature', name='bug_type'),
               nullable=True)
    op.alter_column('bugs', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('bugs', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('bugs', 'priority')
    # ### end Alembic commands ###
